# -*- coding: utf-8 -*-
"""AgenteMistral (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zicKk6LnBhYCMvwxgP4mx9VjuKJXQhoE
"""

# ── Celda 1: Instalación ──────────────────────────────────────────────────────
!pip install -q langchain langchain-mistralai langchain-experimental langchain-community langchain-classic faiss-cpu pandas tabulate

# ── Celda 2: Carga del dataset ────────────────────────────────────────────────
from google.colab import files
import pandas as pd
import io

print("📂 Subí tu archivo 'sales_data_normalizado.csv'")
uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))

print(f"✅ Dataset cargado: {df.shape[0]} filas × {df.shape[1]} columnas")
df.head(3)

# ── Celda 3: Corpus / contexto del dataset ────────────────────────────────────
import json

numeric_summary = df.describe().round(4).to_string()

categorical_cols = ["STATUS", "PRODUCTLINE", "DEALSIZE", "COUNTRY", "TERRITORY", "YEAR_ID", "QTR_ID"]
cat_summary = {col: df[col].value_counts().to_dict() for col in categorical_cols if col in df.columns}

prefix = f"""
Eres un agente experto en análisis de datos de ventas.
Trabajas con un DataFrame de pandas llamado `df` que contiene datos de órdenes de ventas normalizados.

=== ESTRUCTURA DEL DATASET ===
- Total de filas: {df.shape[0]}
- Total de columnas: {df.shape[1]}
- Columnas: {list(df.columns)}

=== DESCRIPCIÓN DE COLUMNAS ===
- ORDERNUMBER: Identificador único de la orden
- QUANTITYORDERED: Cantidad pedida (normalizada con Z-score)
- PRICEEACH: Precio unitario (normalizado con Z-score)
- ORDERLINENUMBER: Número de línea dentro de la orden
- SALES: Monto de venta (normalizado con Z-score)
- ORDERDATE: Fecha de la orden (formato YYYY-MM-DD)
- STATUS: Estado de la orden — valores: {df['STATUS'].unique().tolist()}
- QTR_ID: Trimestre (1 a 4)
- MONTH_ID: Mes (1 a 12)
- YEAR_ID: Año — valores: {df['YEAR_ID'].unique().tolist()}
- PRODUCTLINE: Línea de producto — valores: {df['PRODUCTLINE'].unique().tolist()}
- MSRP: Precio sugerido de fabricante (normalizado)
- PRODUCTCODE: Código de producto
- CUSTOMERNAME: Nombre del cliente
- PHONE / ADDRESSLINE1 / ADDRESSLINE2 / CITY / STATE / POSTALCODE / COUNTRY: Datos de contacto
- TERRITORY: Territorio comercial — valores: {df['TERRITORY'].unique().tolist()}
- CONTACTLASTNAME / CONTACTFIRSTNAME: Contacto del cliente
- DEALSIZE: Tamaño del trato — valores: {df['DEALSIZE'].unique().tolist()}

=== NOTA SOBRE NORMALIZACIÓN ===
Las columnas QUANTITYORDERED, PRICEEACH, SALES y MSRP están normalizadas con Z-score.
Valores positivos están por encima del promedio; negativos, por debajo.
Mencioná siempre que los valores son Z-scores normalizados.

=== ESTADÍSTICAS DESCRIPTIVAS ===
{numeric_summary}

=== DISTRIBUCIÓN DE VARIABLES CATEGÓRICAS ===
{json.dumps(cat_summary, indent=2, ensure_ascii=False)}

Cuando respondas:
1. Usá siempre el DataFrame `df` para tus cálculos.
2. Respondé en español.
3. Aclará cuando los valores son Z-scores normalizados.
4. Sé conciso pero completo.
5. Si no podés responder, decilo claramente.
"""

print("✅ Contexto del dataset construido correctamente.")
print(f"   Longitud del corpus: {len(prefix)} caracteres")

# ── Celda 4: API Key + LLM (Mistral) + Agente Pandas ─────────────────────────
from google.colab import userdata
from langchain_mistralai import ChatMistralAI
from langchain_experimental.agents import create_pandas_dataframe_agent
import os

# API Key desde Colab Secrets (panel 🔑 → MISTRAL_API_KEY)
os.environ["MISTRAL_API_KEY"] = userdata.get("MISTRAL_API_KEY")

# LLM
llm = ChatMistralAI(
    model="mistral-large-latest",
    temperature=0,
)

# Crear el agente
agent = create_pandas_dataframe_agent(
    llm,
    df,
    prefix=prefix,
    verbose=True,
    allow_dangerous_code=True,
    handle_parsing_errors=True,
    agent_type="tool-calling"
)

print("✅ Agente creado correctamente")

# ── Celda 5: Consulta puntual al agente Pandas ───────────────────────────────
def preguntar(pregunta: str):
    print(f"\n{'='*60}")
    print(f"❓ Pregunta: {pregunta}")
    print('='*60)
    respuesta = agent.invoke({"input": pregunta})
    print(f"\n✅ Respuesta:\n{respuesta['output']}")
    return respuesta['output']

# Ejemplo
preguntar("¿Cuántas órdenes hay por cada línea de producto?")

# ── Celda 6: Loop interactivo — Agente Pandas ────────────────────────────────
print("🤖 Agente Pandas listo. Escribí 'salir' para terminar.\n")

while True:
    pregunta = input("Vos: ")
    if pregunta.strip().lower() in ["salir", "exit", "quit"]:
        print("👋 Sesión finalizada.")
        break
    if pregunta.strip() == "":
        continue
    preguntar(pregunta)

"""---
## 🔍 RAG — Recuperación semántica con FAISS + Mistral
"""

# ── Celda 7: Embeddings con Mistral ──────────────────────────────────────────
from langchain_mistralai import MistralAIEmbeddings

embeddings = MistralAIEmbeddings(
    model="mistral-embed",
)

print("✅ Modelo de embeddings cargado: mistral-embed")

# ── Celda 8: Convertir filas del CSV en documentos ───────────────────────────
from langchain_core.documents import Document

documentos = []

for _, row in df.iterrows():
    contenido = (
        f"Orden: {row['ORDERNUMBER']} | "
        f"Cliente: {row['CUSTOMERNAME']} | "
        f"Producto: {row['PRODUCTLINE']} | "
        f"Código: {row['PRODUCTCODE']} | "
        f"Estado: {row['STATUS']} | "
        f"Deal: {row['DEALSIZE']} | "
        f"País: {row['COUNTRY']} | "
        f"Territorio: {row['TERRITORY']} | "
        f"Año: {row['YEAR_ID']} | "
        f"Trimestre: {row['QTR_ID']} | "
        f"Mes: {row['MONTH_ID']} | "
        f"Ventas (Z): {row['SALES']:.4f} | "
        f"Cantidad (Z): {row['QUANTITYORDERED']:.4f} | "
        f"Precio (Z): {row['PRICEEACH']:.4f}"
    )
    metadata = {
        "order_number": int(row["ORDERNUMBER"]),
        "customer": row["CUSTOMERNAME"],
        "product_line": row["PRODUCTLINE"],
        "status": row["STATUS"],
        "country": row["COUNTRY"],
        "year": int(row["YEAR_ID"]),
        "deal_size": row["DEALSIZE"],
    }
    documentos.append(Document(page_content=contenido, metadata=metadata))

print(f"✅ {len(documentos)} documentos generados desde el CSV")

# ── Celda 9: Base vectorial con FAISS ────────────────────────────────────────
from langchain_community.vectorstores import FAISS

# Ajustá LIMITE según tu cuota de API (Mistral cobra por embedding)
LIMITE = 500

vectorstore = FAISS.from_documents(
    documents=documentos[:LIMITE],
    embedding=embeddings,
)

print(f"✅ Base vectorial FAISS creada con {LIMITE} documentos")

# ── Celda 10: Agente RAG (LLM + Retriever + Prompt) ──────────────────────────
from langchain_classic.chains import RetrievalQA
from langchain_core.prompts import PromptTemplate

# Retriever
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 5},
)

# Prompt
rag_prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""
Eres un agente experto en análisis de ventas.
Usás el siguiente contexto recuperado del dataset para responder la pregunta.
Respondé siempre en español. Si no encontrás la respuesta en el contexto, decilo claramente.

RECUERDA: Las columnas SALES, QUANTITYORDERED, PRICEEACH y MSRP están normalizadas con Z-score.

Contexto:
{context}

Pregunta: {question}

Respuesta:"""
)

# Agente RAG
agente_rag = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=True,
    chain_type_kwargs={"prompt": rag_prompt},
)

print("✅ Agente RAG creado correctamente")

# ── Celda 11: Loop interactivo — Agente RAG ───────────────────────────────────
print("🔍 Agente RAG listo. Escribí 'salir' para terminar.\n")

while True:
    pregunta = input("Vos: ")
    if pregunta.strip().lower() in ["salir", "exit", "quit"]:
        print("👋 Sesión finalizada.")
        break
    if pregunta.strip() == "":
        continue

    print(f"\n{'='*60}")
    print(f"❓ Pregunta: {pregunta}")
    print('='*60)

    resultado = agente_rag.invoke({"query": pregunta})

    print(f"\n✅ Respuesta:\n{resultado['result']}")

    print(f"\n📄 Fuentes recuperadas ({len(resultado['source_documents'])}):")
    for i, doc in enumerate(resultado['source_documents'], 1):
        print(f"  [{i}] Orden {doc.metadata['order_number']} | "
              f"{doc.metadata['customer']} | "
              f"{doc.metadata['product_line']} | "
              f"{doc.metadata['status']}")
    print()