# -*- coding: utf-8 -*-
"""agentes ml pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTjs2ZHX-BC28ZBfhrLw-xR5edQsEPnW

# Pipeline Multi-Agente con Transformers

##  Celda 1 – Instalación de dependencias
"""

!pip install -q transformers scikit-learn pandas numpy accelerate sentencepiece

"""
##  Celda 2 – Carga global del modelo LLM (compartido por los 3 agentes)"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODELO_LLM = 'google/flan-t5-base'

print(f'🔄 Cargando LLM compartido: {MODELO_LLM} ...')
_tokenizer = AutoTokenizer.from_pretrained(MODELO_LLM)
_model     = AutoModelForSeq2SeqLM.from_pretrained(MODELO_LLM)

def llamar_llm(prompt):
    """Función auxiliar: llama al LLM y retorna el texto generado."""
    inputs = _tokenizer(prompt, return_tensors='pt')
    outputs = _model.generate(**inputs, max_new_tokens=200, do_sample=False)
    return _tokenizer.decode(outputs[0], skip_special_tokens=True)

print(f'✅ LLM listo y disponible para los 3 agentes.')

"""
## Celda 3 – Carga del Dataset
"""

from google.colab import files
import io
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print('📂 Selecciona el archivo: drug_side_effects_100k_dataset.csv')
uploaded = files.upload()

nombre_archivo = list(uploaded.keys())[0]
df_raw = pd.read_csv(io.BytesIO(uploaded[nombre_archivo])).head(100).reset_index(drop=True)
df_raw.to_csv('drug_side_effects_raw.csv', index=False)

print(f'✅ Dataset cargado: {nombre_archivo}')
print(f'   Filas      : {len(df_raw)}')
print(f'   Columnas   : {list(df_raw.columns)}')
print(f'   Nulos total: {df_raw.isnull().sum().sum()}')
print(f'   Duplicados : {df_raw.duplicated().sum()}')
df_raw.head()

"""---
# AGENTE 1 – NORMALIZADOR

### Celda 4 – Definición de AgenteNormalizador
"""

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

class AgenteNormalizador:
    """
    Agente 1 – Normalizador
    Usa el LLM para analizar el dataset y describir la estrategia,
    luego ejecuta: limpieza → imputación → codificación → escalado.
    """

    def __init__(self, llm_fn, target='recovery_days'):
        self.llm                  = llm_fn
        self.target               = target
        self.scaler               = StandardScaler()
        self.label_encoders       = {}
        self.imputer_num          = SimpleImputer(strategy='median')
        self.imputer_cat          = SimpleImputer(strategy='most_frequent')
        self.log                  = []
        self.columnas_numericas   = []
        self.columnas_categoricas = []

    # ── LLM: analiza el dataset y sugiere estrategia ──────
    def analizar_con_llm(self, df):
        resumen = (
            f"Dataset columns: {list(df.columns)}. "
            f"Rows: {len(df)}. "
            f"Null values per column: {df.isnull().sum().to_dict()}. "
            f"Duplicate rows: {df.duplicated().sum()}. "
            f"Target variable: {self.target}. "
            f"Suggest a data cleaning and preprocessing strategy for this drug side effects dataset."
        )
        respuesta = self.llm(resumen)
        print('\n🤖 LLM – Estrategia de normalización sugerida:')
        print(f'   "{respuesta}"\n')
        self.log.append(f'🤖 LLM estrategia: {respuesta}')

    # ── PASO 1: Limpieza ──────────────────────────────────
    def limpiar(self, df):
        n0 = len(df)
        # Eliminar duplicados
        df = df.drop_duplicates().reset_index(drop=True)
        # Eliminar columnas no útiles para el modelo
        cols_drop = ['patient_id', 'report_date', 'treatment_start_date']
        df = df.drop(columns=[c for c in cols_drop if c in df.columns])
        # Eliminar filas sin target
        df = df.dropna(subset=[self.target])
        # Filtrar valores raros en target
        df = df[df[self.target] >= 0]
        self.log.append(f'🗑️  Duplicados eliminados    : {n0 - len(df)}')
        self.log.append(f'🔍 Filas tras limpieza       : {len(df)} (inicio: {n0})')
        return df.reset_index(drop=True)

    # ── PASO 2: Clasificar columnas ───────────────────────
    def clasificar_columnas(self, df):
        self.columnas_categoricas = df.select_dtypes(include=['object']).columns.tolist()
        self.columnas_numericas   = [
            c for c in df.select_dtypes(include=[np.number]).columns
            if c != self.target
        ]
        self.log.append(f'📌 Numéricas  ({len(self.columnas_numericas)})   : {self.columnas_numericas}')
        self.log.append(f'🏷️  Categóricas({len(self.columnas_categoricas)})   : {self.columnas_categoricas}')
        return df

    # ── PASO 3: Imputación ────────────────────────────────
    def imputar(self, df):
        nulos_antes = df.isnull().sum().sum()
        if self.columnas_numericas:
            df[self.columnas_numericas] = self.imputer_num.fit_transform(df[self.columnas_numericas])
        if self.columnas_categoricas:
            # Use .values.reshape(-1, 1) to ensure 2D array for imputer
            df[self.columnas_categoricas] = self.imputer_cat.fit_transform(df[self.columnas_categoricas])
        self.log.append(f'🩹 Imputación: {nulos_antes} nulos → {df.isnull().sum().sum()} nulos')
        return df

    # ── PASO 4: Codificación ──────────────────────────────
    def codificar(self, df):
        for col in self.columnas_categoricas:
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col].astype(str))
            self.label_encoders[col] = le
        self.log.append(f'🔢 LabelEncoder aplicado     : {self.columnas_categoricas}')
        return df

    # ── PASO 5: Escalado ──────────────────────────────────
    def escalar(self, df):
        if self.columnas_numericas:
            df[self.columnas_numericas] = self.scaler.fit_transform(df[self.columnas_numericas])
        self.log.append(f'⚖️  StandardScaler aplicado  : {len(self.columnas_numericas)} columnas')
        return df

    # ── Pipeline completo ─────────────────────────────────
    def ejecutar(self, csv_path):
        print('═'*55)
        print('  🧹 AGENTE 1 – NORMALIZADOR')
        print('═'*55)
        df = pd.read_csv(csv_path)
        self.log.append(f'📥 CSV cargado               : {len(df)} filas')

        self.analizar_con_llm(df)   # ← LLM analiza y sugiere

        df = self.limpiar(df)
        df = self.clasificar_columnas(df)
        df = self.imputar(df)
        df = self.codificar(df)
        df = self.escalar(df)

        df.to_csv('drug_side_effects_clean.csv', index=False)
        self.log.append(f'💾 CSV limpio guardado       : drug_side_effects_clean.csv ({len(df)} filas)')

        print('\n'.join(self.log))
        print('\n✅ Agente 1 finalizado.')
        return df, self.log

"""### Celda 5 – Ejecutar Agente 1"""

agente1 = AgenteNormalizador(llm_fn=llamar_llm)
df_limpio, log_agente1 = agente1.ejecutar('drug_side_effects_raw.csv')

"""### Celda 6 – Verificar dataset limpio"""

print(f'📐 Shape  : {df_limpio.shape}')
print(f'✅ Nulos  : {df_limpio.isnull().sum().sum()}')
df_limpio.describe().round(3)

"""---
# AGENTE 2 – ENTRENADOR

### Celda 7 – Definición de AgenteEntrenador
"""

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import time

class AgenteEntrenador:
    """
    Agente 2 – Entrenador
    Usa el LLM para decidir qué modelos y configuración aplicar,
    luego ejecuta: validación cruzada → entrenamiento → selección del mejor.
    """

    def __init__(self, llm_fn, target='recovery_days'):
        self.llm              = llm_fn
        self.target           = target
        self.resultados       = {}
        self.mejor_modelo     = None
        self.mejor_nombre     = ''
        self.metricas_finales = {}
        # Modelos fijos — el LLM justifica por qué son adecuados
        self.modelos = {
            'Ridge Regression'  : Ridge(alpha=1.0),
            'Random Forest'     : RandomForestRegressor(
                                      n_estimators=100, max_depth=5,
                                      random_state=42, n_jobs=-1),
            'Gradient Boosting' : GradientBoostingRegressor(
                                      n_estimators=100, max_depth=3,
                                      learning_rate=0.1, random_state=42)
        }

    # ── LLM: decide estrategia de entrenamiento ───────────
    def decidir_con_llm(self, df):
        prompt = (
            f"You have a clean drug side effects dataset with {len(df)} rows and "
            f"{df.shape[1]-1} features. Target variable: recovery_days (continuous, regression). "
            f"Features: {list(df.drop(columns=[self.target]).columns)}. "
            f"Which machine learning models would you recommend for this regression task "
            f"and why? Choose from: Ridge Regression, Random Forest, Gradient Boosting."
        )
        respuesta = self.llm(prompt)
        print('\n🤖 LLM – Decisión de modelos a entrenar:')
        print(f'   "{respuesta}"\n')
        return respuesta

    # ── LLM: interpreta resultado del entrenamiento ───────
    def interpretar_con_llm(self, mejor_nombre, r2, mae):
        prompt = (
            f"After training Ridge Regression, Random Forest, and Gradient Boosting "
            f"on a drug side effects dataset predicting recovery days, the best model is {mejor_nombre} "
            f"with R2={r2} and MAE={mae}. "
            f"Briefly explain why this model outperformed the others."
        )
        respuesta = self.llm(prompt)
        print('\n🤖 LLM – Explicación del mejor modelo:')
        print(f'   "{respuesta}"\n')
        return respuesta

    # ── División train/test ───────────────────────────────
    def dividir(self, df):
        X = df.drop(columns=[self.target])
        y = df[self.target]
        X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)
        print(f'📐 Train: {len(X_tr)} filas | Test: {len(X_te)} filas')
        return X_tr, X_te, y_tr, y_te

    # ── Validación + entrenamiento ────────────────────────
    def validar_y_entrenar(self, X_tr, X_te, y_tr, y_te):
        print('\n🔄 Validación cruzada (5-fold) + Entrenamiento')
        print('─'*50)
        for nombre, modelo in self.modelos.items():
            print(f'\n▶ {nombre}')
            t0     = time.time()
            cv     = cross_val_score(modelo, X_tr, y_tr, cv=5, scoring='r2', n_jobs=-1)
            modelo.fit(X_tr, y_tr)
            y_pred = modelo.predict(X_te)
            mae    = mean_absolute_error(y_te, y_pred)
            rmse   = np.sqrt(mean_squared_error(y_te, y_pred))
            r2     = r2_score(y_te, y_pred)
            t      = time.time() - t0
            self.resultados[nombre] = {
                'cv_r2_mean': round(cv.mean(), 4),
                'cv_r2_std' : round(cv.std(),  4),
                'test_MAE'  : round(mae,  4),
                'test_RMSE' : round(rmse, 4),
                'test_R2'   : round(r2,   4),
                'tiempo_s'  : round(t,    2),
                'modelo'    : modelo,
                'y_pred'    : y_pred
            }
            print(f'   CV  R²  : {cv.mean():.4f} ± {cv.std():.4f}')
            print(f'   Test R² : {r2:.4f}  |  MAE: {mae:.4f}  |  RMSE: {rmse:.4f}')

    # ── Selección ─────────────────────────────────────────
    def seleccionar(self):
        mejor = max(self.resultados.items(), key=lambda x: x[1]['test_R2'])
        self.mejor_nombre     = mejor[0]
        self.mejor_modelo     = mejor[1]['modelo']
        self.metricas_finales = {k: v for k, v in mejor[1].items() if k not in ['modelo','y_pred']}
        print('\n' + '═'*50)
        print(f'  🏆 MEJOR MODELO : {self.mejor_nombre}')
        print(f'     R²   = {self.metricas_finales["test_R2"]}')
        print(f'     MAE  = {self.metricas_finales["test_MAE"]}')
        print(f'     RMSE = {self.metricas_finales["test_RMSE"]}')
        print('═'*50)

    # ── Pipeline completo ─────────────────────────────────
    def ejecutar(self, df):
        print('═'*55)
        print('  🏋️  AGENTE 2 – ENTRENADOR')
        print('═'*55)

        decision_llm = self.decidir_con_llm(df)   # ← LLM decide estrategia

        X_tr, X_te, y_tr, y_te = self.dividir(df)
        self.validar_y_entrenar(X_tr, X_te, y_tr, y_te)
        self.seleccionar()

        explicacion_llm = self.interpretar_con_llm(
            self.mejor_nombre,
            self.metricas_finales['test_R2'],
            self.metricas_finales['test_MAE']
        )

        print('✅ Agente 2 finalizado.')
        return (
            self.mejor_nombre,
            self.mejor_modelo,
            self.metricas_finales,
            self.resultados,
            decision_llm,
            explicacion_llm
        )

"""### Celda 8 – Ejecutar Agente 2"""

agente2 = AgenteEntrenador(llm_fn=llamar_llm)
(
    mejor_nombre,
    mejor_modelo,
    metricas_finales,
    todos_resultados,
    decision_llm,
    explicacion_llm
) = agente2.ejecutar(df_limpio)

"""### Celda 9 – Tabla comparativa de modelos"""

tabla = pd.DataFrame([
    {
        'Modelo'        : nom,
        'CV R² (media)' : res['cv_r2_mean'],
        'CV R² (std)'   : res['cv_r2_std'],
        'Test MAE'      : res['test_MAE'],
        'Test RMSE'     : res['test_RMSE'],
        'Test R²'       : res['test_R2'],
        'Tiempo (s)'    : res['tiempo_s']
    }
    for nom, res in todos_resultados.items()
]).sort_values('Test R²', ascending=False).reset_index(drop=True)

print('📊 Comparativa de modelos:')
tabla

"""---
# AGENTE 3 – COMUNICADOR

### Celda 10 – Definición de AgenteComunicador
"""

import textwrap

class AgenteComunicador:
    """
    Agente 3 – Comunicador
    Usa el LLM para generar cada sección del reporte
    en lenguaje natural a partir de los resultados del pipeline.
    """

    def __init__(self, llm_fn, modelo_nombre):
        self.llm    = llm_fn
        self.nombre = modelo_nombre

    def _seccion(self, titulo, prompt):
        """Llama al LLM y muestra progreso."""
        print(f'  ✍️  Generando: {titulo}...')
        texto = self.llm(prompt)
        return texto

    # ── Sección 1 ─────────────────────────────────────────
    def s_dataset(self, n_raw, n_clean, n_cols):
        return self._seccion('Descripción del dataset',
            f"Describe a drug side effects dataset used for machine learning. "
            f"It originally had {n_raw} rows. After cleaning it has {n_clean} rows "
            f"and {n_cols} features. Target: recovery_days (number of days to recover).")

    # ── Sección 2 ─────────────────────────────────────────
    def s_preprocesamiento(self, log):
        pasos = '; '.join([e for e in log if not e.startswith('🤖')])
        return self._seccion('Preprocesamiento',
            f"Summarize in plain language the following data preprocessing pipeline log: {pasos}")

    # ── Sección 3 ─────────────────────────────────────────
    def s_comparativa(self, todos, decision_llm):
        comp = ' | '.join([f"{n}: R2={r['test_R2']}, MAE={r['test_MAE']}" for n, r in todos.items()])
        return self._seccion('Comparativa de modelos',
            f"The following models were trained on a drug side effects dataset: {comp}. "
            f"Prior recommendation was: {decision_llm}. "
            f"Summarize the comparison and explain which model performed best.")

    # ── Sección 4 ─────────────────────────────────────────
    def s_metricas(self, nombre, r2, mae, rmse, cv_r2):
        return self._seccion('Interpretación de métricas',
            f"Interpret these regression metrics for the best model ({nombre}) "
            f"predicting recovery days in drug patients: R2={r2}, MAE={mae}, RMSE={rmse}, CV_R2={cv_r2}. "
            f"Explain what each metric means in practical medical terms.")

    # ── Sección 5 ─────────────────────────────────────────
    def s_conclusion(self, nombre, r2, explicacion_llm):
        return self._seccion('Conclusiones y recomendaciones',
            f"Write a conclusion for a machine learning project predicting drug recovery days. "
            f"Best model: {nombre}, R2={r2}. Context: {explicacion_llm}. "
            f"Give two concrete recommendations to improve future performance.")

    # ── Imprimir reporte ──────────────────────────────────
    def imprimir(self, secciones_dict):
        sep = '═' * 62
        lin = '─' * 62
        iconos = {
            'Descripción del dataset'         : '📊',
            'Preprocesamiento'                : '🧹',
            'Comparativa de modelos'          : '🏆',
            'Interpretación de métricas'      : '📈',
            'Conclusiones y recomendaciones'  : '💡'
        }
        print('\n' + sep)
        print('         📋  REPORTE FINAL – PIPELINE ML MULTI-AGENTE')
        print(sep)
        print(f'  LLM utilizado : {self.nombre}')
        print(f'  Framework     : HuggingFace Transformers')
        print(lin)
        for titulo, texto in secciones_dict.items():
            ic = iconos.get(titulo, '📌')
            print(f'\n{ic}  {titulo.upper()}')
            print(lin)
            print(textwrap.fill(texto, width=60,
                                initial_indent='  ', subsequent_indent='  '))
        print('\n' + sep)
        print('  ✅  Reporte generado íntegramente por el LLM (Agente 3)')
        print(sep)

    # ── Pipeline completo ─────────────────────────────────
    def ejecutar(self, log_norm, mejor_nombre, metricas, todos,
                 decision_llm, explicacion_llm, n_raw, n_clean, n_cols):
        print('═'*55)
        print('  📝 AGENTE 3 – COMUNICADOR')
        print('═'*55)
        print('Generando reporte con LLM (5 secciones)...\n')

        secciones = {}
        secciones['Descripción del dataset']        = self.s_dataset(n_raw, n_clean, n_cols)
        secciones['Preprocesamiento']               = self.s_preprocesamiento(log_norm)
        secciones['Comparativa de modelos']         = self.s_comparativa(todos, decision_llm)
        secciones['Interpretación de métricas']     = self.s_metricas(
            mejor_nombre,
            metricas['test_R2'], metricas['test_MAE'],
            metricas['test_RMSE'], metricas['cv_r2_mean']
        )
        secciones['Conclusiones y recomendaciones'] = self.s_conclusion(
            mejor_nombre, metricas['test_R2'], explicacion_llm
        )

        self.imprimir(secciones)
        print('\n✅ Agente 3 finalizado.')
        return secciones

"""### Celda 11 – Ejecutar Agente 3"""

n_features = df_limpio.drop(columns=['recovery_days']).shape[1]

agente3 = AgenteComunicador(llm_fn=llamar_llm, modelo_nombre=MODELO_LLM)

secciones_reporte = agente3.ejecutar(
    log_norm        = log_agente1,
    mejor_nombre    = mejor_nombre,
    metricas        = metricas_finales,
    todos           = todos_resultados,
    decision_llm    = decision_llm,
    explicacion_llm = explicacion_llm,
    n_raw           = len(df_raw),
    n_clean         = len(df_limpio),
    n_cols          = n_features
)

"""---
## Celda 12 – Resumen final del Pipeline
"""

print('━'*60)
print('  🗂️  RESUMEN PIPELINE MULTI-AGENTE')
print('━'*60)
print(f'\n  🔧 LLM compartido : {MODELO_LLM}')
print(f'\n  📂 Dataset        : Drug Side Effects (100 filas)')
print(f'     Filas raw     : {len(df_raw)}')
print(f'     Filas limpias : {len(df_limpio)}')

print(f'\n  🧹 Agente 1 – Normalizador  [usa LLM para analizar esquema]')
for e in log_agente1:
    print(f'     {e}')

print(f'\n  🏋️  Agente 2 – Entrenador    [usa LLM para decidir modelos y explicar resultado]')
for nom, res in todos_resultados.items():
    tag = '  ← MEJOR' if nom == mejor_nombre else ''
    print(f'     {nom:<22} R²={res["test_R2"]:.4f}  MAE={res["test_MAE"]:.4f}{tag}')

print(f'\n  📝 Agente 3 – Comunicador   [usa LLM para generar reporte completo]')
print(f'     Secciones generadas : {len(secciones_reporte)}')

print('\n' + '━'*60)
print('  ✅ Pipeline ejecutado exitosamente.')
print('━'*60)